version: '3'

# services:
#     backend:
#         build: ./backend
#         volumes:
#             - ./backend:/usr/src/app
#         ports:
#             - 5001:80
#         environment: 
#             - FLASK_ENV=development
            
services:
    backend:
        build: ./backend
        expose: 
            - 5000
        ports:
            - 5000:5000
        volumes:
            - ./backend:/usr/src/app
        environment: 
            - FLASK_ENV=development
            - FLASK_APP=app.py
            - FLASK_DEBUG=1
    frontend:
        build: ./frontend
        expose: 
            - 3000
        ports: 
            - 3000:3000
        volumes: 
            - ./frontend/src:/usr/src/app/src
            - ./frontend/public:/usr/src/app/public
        links: 
            - "backend:backend"
            